export const ADD_MORE_BOOKS = 'LOAD_MORE_BOOKS';

export const SET_BOOKS = 'SEARCH_BOOKS';

export const CHANGE_SEARCH_PARAMS = 'SET_SEARCH_PARAMS';

export const TOGGLE_SEARCH_LOADER = 'TOGGLE_SEARCH_LOADER';

export const TOGGLE_PAGINATION_LOADER = 'TOGGLE_PAGINATION_LOADER';

export const SET_BOOKS_COUNT = 'SET_BOOKS_COUNT'